name: Autofix HTML and Sitemap

on:
  workflow_dispatch:   # manual trigger only

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run autofix scripts
        run: |
          npm install
          node scripts/verify-includes.js --fix || true
          node scripts/sitemap-generator.js || true

      - name: Commit and push fixes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Autofix: includes and sitemap update" || echo "No changes to commit"
          git push origin main
