name: Cleanup Test Protection Workflow

on:
  workflow_dispatch:   # manual trigger only

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove test-protection workflow
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          rm -f .github/workflows/test-protection.yml
          git add .github/workflows/test-protection.yml || true
          git commit -m "Cleanup: remove test-protection workflow" || echo "No changes to commit"
          git push origin main
